### ISSUE TITLE
Access A Variable from torch.autograd.function.GradReverseBackward

### ISSUE THREAD

**Issue by akul-goyal** [YU1ut/openset-DA#8]
I am getting a “AttributeError: ‘GradReverseBackward’ object has no attribute ‘lambd’” on the backward propagation. I modified line 65 in models.py to GradReverse(lambd).apply(x).

**Comment by tailuoaoteman** [comment]
这是来自QQ邮箱的自动回复邮件。
 
已收到您的邮件。

**Comment by akul-goyal** [comment]
https://pytorch.org/tutorials/beginner/examples_autograd/two_layer_net_custom_function.html
